In [3]:
import pandas as pd

**read_csv()**
csv 파일 읽어오기

In [4]:
titanic_df = pd.read_csv('titanic_train.csv')
print('titanic 변수 type:', type(titanic_df))

titanic 변수 type: <class 'pandas.core.frame.DataFrame'>


**head()**
맨 앞 일부 데이터 추출

In [3]:
titanic_df.head(5)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

DataFrame 생성

In [5]:
dic1 = {'Name': ['Chulmin', 'Eunkyung', 'Jinwoong', 'Soobeom'],
       'Year': [2011, 2016, 2015, 2015]}
data_df = pd.DataFrame(dic1) # key가 컬럼이 된다
print(data_df)
print('#'*30)

# 컬럼명 지정
data_df = pd.DataFrame(dic1, columns=['Name', 'Year', 'Age'])
print(data_df)
print('#'*30)

# 인덱스 값 지정
data_df = pd.DataFrame(dic1, index=['one', 'two', 'three', 'four'])
print(data_df)
print('#'*30)

       Name  Year
0   Chulmin  2011
1  Eunkyung  2016
2  Jinwoong  2015
3   Soobeom  2015
##############################
       Name  Year  Age
0   Chulmin  2011  NaN
1  Eunkyung  2016  NaN
2  Jinwoong  2015  NaN
3   Soobeom  2015  NaN
##############################
           Name  Year
one     Chulmin  2011
two    Eunkyung  2016
three  Jinwoong  2015
four    Soobeom  2015
##############################


In [10]:
print(type(data_df['Name']))

<class 'pandas.core.series.Series'>


컬럼명, 인덱스 출력하기

In [13]:
print("columns:", titanic_df.columns)
print("index:", titanic_df.index) # meta 정보가 출력

columns: Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')
index: RangeIndex(start=0, stop=891, step=1)


DF로부터 Series 추출 및 DF 필터링

In [16]:
series = titanic_df['Name']
print(series.head(3))
print(type(series))
print('#'*30)

filtered_df = titanic_df[['Name', 'Age']]
print(filtered_df.head(3))
print('#'*30)

# bracket을 한 번 더 감싸면 1 column 이어도 DataFrame으로 가져오게 된다. 컬럼명이 확인됨.
one_col_df = titanic_df[['Name']]
print(one_col_df.head(3))
print(type(one_col_df))

0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
Name: Name, dtype: object
<class 'pandas.core.series.Series'>
##############################
                                                Name   Age
0                            Braund, Mr. Owen Harris  22.0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                             Heikkinen, Miss. Laina  26.0
##############################
                                                Name
0                            Braund, Mr. Owen Harris
1  Cumings, Mrs. John Bradley (Florence Briggs Th...
2                             Heikkinen, Miss. Laina
<class 'pandas.core.frame.DataFrame'>


**shape**
DataFrame의 행, 열 크기 조사

In [18]:
print(titanic_df.shape)

(891, 12)


**info()**
컬럼명, 데이터타입, Null 건수 등 정보 제공

In [20]:
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


**describe()**
컬럼별로 평균, 표준편차 등 통계값 제공

In [21]:
titanic_df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

**value_counts()**
유니크한 데이터값 정보를 제공. Series 객체에서만 호출 가능

In [23]:
value_counts = titanic_df['Age'].value_counts()
print(value_counts)
# 왼쪽이 값이며 index로 사용. 오른쪽이 개수

24.00    30
22.00    27
18.00    26
19.00    25
30.00    25
         ..
55.50     1
70.50     1
66.00     1
23.50     1
0.42      1
Name: Age, Length: 88, dtype: int64


**sort_values()**
특정 컬럼 기준으로 정렬

In [41]:
titanic_df[['Name', 'Age']].sort_values(by='Age', ascending=False)

Name   Age
630      Barkworth, Mr. Algernon Henry Wilson  80.0
851                       Svensson, Mr. Johan  74.0
493                   Artagaveytia, Mr. Ramon  71.0
96                  Goldschmidt, Mr. George B  71.0
116                      Connors, Mr. Patrick  70.5
..                                        ...   ...
859                          Razi, Mr. Raihed   NaN
863         Sage, Miss. Dorothy Edith "Dolly"   NaN
868               van Melkebeke, Mr. Philemon   NaN
878                        Laleff, Mr. Kristo   NaN
888  Johnston, Miss. Catherine Helen "Carrie"   NaN

[891 rows x 2 columns]

**DataFrame <-> list, ndarray, dict 변환**

In [30]:
import numpy as np

col_name = ['col1']
list1 = [1,2,3]
ndarray1 = np.array(list1) # ndarray 생성
print(ndarray1)
print('#'*30)

# 리스트 -> 데이터프레임 (컬럼값 지정 필요)
df1 = pd.DataFrame(list1, columns=col_name)
print(df1)
print('#'*30)

# ndarray -> 데이터프레임 (컬럼값 지정 필요)
df2 = pd.DataFrame(ndarray1, columns=col_name)
print(df2)
print('#'*30)

# dict -> 데이터프레임
dict = {'col1': [1,11], 'col2': [2,22], 'col3': [3,33]}
df_dict = pd.DataFrame(dict)
print(df_dict)
print('#'*30)

[1 2 3]
##############################
   col1
0     1
1     2
2     3
##############################
   col1
0     1
1     2
2     3
##############################
   col1  col2  col3
0     1     2     3
1    11    22    33
##############################


In [34]:
# 데이터프레임 -> ndarray
array3 = df_dict.values
print("type:", type(array3))
print(array3, array3.shape)
print(array3)
print('#'*30)

# 데이터프레임 -> list
list3 = df_dict.values.tolist()
print("type:", type(list3))
print(list3)
print('#'*30)

# 데이터프레임 -> dict
dict3 = df_dict.to_dict()
print("type:", type(dict3))
print(dict3)
print('#'*30)

type: <class 'numpy.ndarray'>
[[ 1  2  3]
 [11 22 33]] (2, 3)
[[ 1  2  3]
 [11 22 33]]
##############################
type: <class 'list'>
[[1, 2, 3], [11, 22, 33]]
##############################
type: <class 'dict'>
{'col1': {0: 1, 1: 11}, 'col2': {0: 2, 1: 22}, 'col3': {0: 3, 1: 33}}
##############################


**데이터 삭제**

In [43]:
titanic_drop_df = titanic_df.drop('Pclass', axis=1)
print(titanic_df.head(3))
print('#'*30)
print(titanic_drop_df.head(3))

   PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
##############################
   PassengerId  Survived                                               Name  \
0            1         0                            Braund, Mr. Owen Harris   
1            2         1  Cumings, Mrs. John Bradley (Florence Briggs Th...   
2            3         1                             Heikkinen, Mi

**Index 객체**

In [45]:
indexes = titanic_df.index
print(indexes) # Index에는 RangeIndex 말고 DatetimeIndex 등도 있음

RangeIndex(start=0, stop=891, step=1)


In [49]:
value_counts = titanic_df['Pclass'].value_counts() # 유일값 추출
print(value_counts)
print(type(value_counts))
print('#'*30)

new_value_counts = value_counts.reset_index(inplace=False)
print(new_value_counts)

3    491
1    216
2    184
Name: Pclass, dtype: int64
<class 'pandas.core.series.Series'>
##############################
   index  Pclass
0      3     491
1      1     216
2      2     184


**iloc[], loc 연산자**

In [60]:
print(data_df)
print('#'*30)

print(data_df.iloc[0:2,1])
print('#'*30)

print(data_df.loc[['two', 'four'], 'Year']) # 명칭 기반 -> ['인덱스', '컬럼명']

           Name  Year
one     Chulmin  2011
two    Eunkyung  2016
three  Jinwoong  2015
four    Soobeom  2015
##############################
one    2011
two    2016
Name: Year, dtype: int64
##############################
two     2016
four    2015
Name: Year, dtype: int64


불린 인덱싱

In [71]:
titanic_df[titanic_df['Age']>60][['Name', 'Age']].head(5)

Name   Age
33            Wheadon, Mr. Edward H  66.0
54   Ostby, Mr. Engelhart Cornelius  65.0
96        Goldschmidt, Mr. George B  71.0
116            Connors, Mr. Patrick  70.5
170       Van der hoef, Mr. Wyckoff  61.0

In [72]:
titanic_df.loc[titanic_df['Age']>60, ['Name','Age']].head(3)

Name   Age
33           Wheadon, Mr. Edward H  66.0
54  Ostby, Mr. Engelhart Cornelius  65.0
96       Goldschmidt, Mr. George B  71.0

In [73]:
titanic_df[ (titanic_df['Age']>60) & titanic_df['Pclass'] == 1].head(3)

PassengerId  Survived  Pclass                            Name   Sex  \
54            55         0       1  Ostby, Mr. Engelhart Cornelius  male   
96            97         0       1       Goldschmidt, Mr. George B  male   
116          117         0       3            Connors, Mr. Patrick  male   

      Age  SibSp  Parch    Ticket     Fare Cabin Embarked  
54   65.0      0      1    113509  61.9792   B30        C  
96   71.0      0      0  PC 17754  34.6542    A5        C  
116  70.5      0      0    370369   7.7500   NaN        Q

In [78]:
cond1 = titanic_df['Age']>60
cond2 = titanic_df['Pclass'] == 1
print(titanic_df[cond1 & cond2])

     PassengerId  Survived  Pclass                                       Name  \
54            55         0       1             Ostby, Mr. Engelhart Cornelius   
96            97         0       1                  Goldschmidt, Mr. George B   
170          171         0       1                  Van der hoef, Mr. Wyckoff   
252          253         0       1                  Stead, Mr. William Thomas   
275          276         1       1          Andrews, Miss. Kornelia Theodosia   
438          439         0       1                          Fortune, Mr. Mark   
456          457         0       1                  Millet, Mr. Francis Davis   
493          494         0       1                    Artagaveytia, Mr. Ramon   
545          546         0       1               Nicholson, Mr. Arthur Ernest   
555          556         0       1                         Wright, Mr. George   
625          626         0       1                      Sutton, Mr. Frederick   
630          631         1  

**Aggregation 함수**

In [80]:
titanic_df[['Age', 'Fare']].mean(axis=0)

Age     29.699118
Fare    32.204208
dtype: float64

**GroupBy**

In [81]:
titanic_groupby = titanic_df.groupby(by='Pclass') # 그냥 groupby만 하면 값이 나오지 않는다
print(titanic_groupby)
print(type(titanic_groupby))

<class 'pandas.core.groupby.generic.DataFrameGroupBy'>


In [82]:
titanic_groupby = titanic_df.groupby(by='Pclass').count()
print(titanic_groupby)

        PassengerId  Survived  Name  Sex  Age  SibSp  Parch  Ticket  Fare  \
Pclass                                                                      
1               216       216   216  216  186    216    216     216   216   
2               184       184   184  184  173    184    184     184   184   
3               491       491   491  491  355    491    491     491   491   

        Cabin  Embarked  
Pclass                   
1         176       214  
2          16       184  
3          12       491  


In [83]:
print(type(titanic_groupby))
print(titanic_groupby.shape)
print(titanic_groupby.index)

<class 'pandas.core.frame.DataFrame'>
(3, 11)
Int64Index([1, 2, 3], dtype='int64', name='Pclass')


In [86]:
titanic_groupby = titanic_df.groupby('Pclass')[['PassengerId', 'Survived']].count()
print(titanic_groupby)

# 메모리를 더 효율적으로 사용하려면
titanic_groupby = titanic_df[['PassengerId', 'Survived', 'Pclass']].groupby('Pclass').count()
print(titanic_groupby)

        PassengerId  Survived
Pclass                       
1               216       216
2               184       184
3               491       491
        PassengerId  Survived
Pclass                       
1               216       216
2               184       184
3               491       491


In [89]:
# groupby한 후 함수를 여러개 사용해 통계를 보고 싶다면
titanic_df.groupby('Pclass')[['Age', 'Pclass']].agg([max, min])

Age       Pclass    
         max   min    max min
Pclass                       
1       80.0  0.92      1   1
2       70.0  0.67      2   2
3       74.0  0.42      3   3

In [91]:
agg_format = {'Age': 'max', 'SibSp': 'sum', 'Fare': 'mean'}
titanic_df.groupby('Pclass').agg(agg_format)

Age  SibSp       Fare
Pclass                        
1       80.0     90  84.154687
2       70.0     74  20.662183
3       74.0    302  13.675550

**결측치 처리**

In [92]:
titanic_df.isna().head(3)

PassengerId  Survived  Pclass   Name    Sex    Age  SibSp  Parch  Ticket  \
0        False     False   False  False  False  False  False  False   False   
1        False     False   False  False  False  False  False  False   False   
2        False     False   False  False  False  False  False  False   False   

    Fare  Cabin  Embarked  
0  False   True     False  
1  False  False     False  
2  False   True     False

In [93]:
titanic_df.isna().sum() # 결측치 개수. count를 하면 결측치가 안 나오고 sum을 해야 함에 주의

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [5]:
titanic_df['Cabin'] = titanic_df['Cabin'].fillna('C000')

titanic_df['Age'] = titanic_df['Age'].fillna(titanic_df['Age'].mean)

titanic_df.isna().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       2
dtype: int64

lambda

In [7]:
a=[1,2,3]
squares = map(lambda x: x**2, a)
print(squares)
print(list(squares))

[1, 4, 9]


In [9]:
titanic_df['Name_Length'] = titanic_df['Name'].apply(lambda x : len(x))
print(titanic_df['Name_Length'])

0      23
1      51
2      22
3      44
4      24
       ..
886    21
887    28
888    40
889    21
890    19
Name: Name_Length, Length: 891, dtype: int64


In [10]:
titanic_df['Child_Adult'] = titanic_df['Age'].apply(lambda x : 'Child' if x <= 15 else 'Adult')
print(titanic_df['Child_Adult'])

TypeError: '<=' not supported between instances of 'method' and 'int'