In [2]:
import numpy as np

In [2]:
list1 = [1,2,3]
print(list1)
print("list1 type:",type(list1))

array1 = np.array(list1)
print(array1)
print("array1 type:", type(array1))

[1, 2, 3]
list1 type: <class 'list'>
[1 2 3]
array1 type: <class 'numpy.ndarray'>


Shape과 차원

In [4]:
array1 = np.array([1,2,3])
print(array1)
print(array1.shape)

array2 = np.array([[1,2,3],[4,5,6]])
print(array2)
print(array2.shape)

# 1차원같지만 2차원
array3 = np.array([[1,2,3]])
print(array3)
print(array3.shape)
print(array3.ndim)

[1 2 3]
(3,)
[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 2 3]]
(1, 3)
2


데이터 타입

In [5]:
print(array1.dtype)

int32


axis 기반의 연산함수

In [6]:
print(array2)

print(array2.sum())
print(array2.sum(axis=0))
print(array2.sum(axis=1))

[[1 2 3]
 [4 5 6]]
21
[5 7 9]
[ 6 15]


ndarray 편하게 생성하기

In [8]:
print(np.arange(10))
print(np.zeros((3,2), dtype='int32'))
print(np.ones((3,2))) # default는 실수형

[0 1 2 3 4 5 6 7 8 9]
[[0 0]
 [0 0]
 [0 0]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [9]:
array = np.arange(10)
print(array.reshape(2,5))
print(array.reshape(-1,2)) # -1로 적은 axis는 가변. 다른 axis의 조건에 따라 자동으로 맞춰짐

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


인덱싱

In [3]:
array1 = np.arange(start=1, stop=10)
print('array1:', array1)

array1: [1 2 3 4 5 6 7 8 9]


In [4]:
array2d = array1.reshape(3,3)
print(array2d)

print('array2d[2,2]=', array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[2,2]= 9


슬라이싱

In [5]:
array3 = array2d[[0,1],2]
print(array3)

[3 6]


불린 인덱싱

In [7]:
print(array1 > 5)

var1 = array1 > 5
print("var1:", var1)
print(type(var1))
print(var1.dtype)

[False False False False False  True  True  True  True]
var1: [False False False False False  True  True  True  True]
<class 'numpy.ndarray'>
bool


In [8]:
array3 = array1[array1>5]
print(array3)

[6 7 8 9]


argSort

In [9]:
name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array = np.array([78, 95, 84, 98, 88])

sort_indices = np.argsort(score_array)
print("sort_indices:", sort_indices)

name_array_sort = name_array[sort_indices]
print(name_array_sort)

sort_indices: [0 2 4 1 3]
['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


기타

In [5]:
# 인덱싱
arr = np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [6]:
# 1행 이전까지를 가져오기
arr[:1]

array([[1, 2, 3, 4]])

In [7]:
# 1행~ 을 가져오기
arr[1:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [8]:
# 행은 전부다, 2열만
arr[:,2]

array([ 3,  7, 11])